config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :profiles
  root "welcome#about"

  get '/contact', to: "contacts#form"
  post '/contact', to: "contacts#mail"

  get 'registrations/new'

  # post 'home/action'

  get '/signup', to: "registrations#new"
  post '/signup', to: "registrations#create"

  get 'login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  # get 'users/:id', to: "users#show", as: "profile"

  resources :chatrooms, param: :slug
  resources :messages

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  has_many :connects, dependent: :destroy
  
  validates :topic, presence: true, uniqueness: true, case_sensitive: false
  before_validation :sanitize, :slugify


  def to_param
    self.slug
  end

  def slugify
    self.slug = self.topic.downcase.gsub(" ", "-")
  end

  def sanitize
    self.topic = self.topic.strip
  end
end

app/models/connect.rb
class Connect < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom

  validates :article, presence: true 
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

   mount_uploader :avatar, AvatarUploader
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  attr_accessor :password

  before_save :encrypt_password
  after_save :clear_password


  has_many :messages, dependent: :destroy
  has_many :chatrooms, through: :messages
  has_many :connects, dependent: :destroy
  has_one :profile, dependent: :destroy

  # EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  validates_length_of :password, in: 6..20, on: :create

  after_create :assign_default_role


  def assign_default_role
    self.add_role(:member) if self.roles.blank?
  end

  def admin?
    has_role?(:admin)
  end

  def self.authenticate(username="", login_password="")

    user = User.find_by_username(username)

    if user && user.match_password(login_password)
      return user
    else
      return false
    end
  end

  def match_password(login_password="")
    encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
  end

  def encrypt_password
    unless password.blank?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def clear_password
    self.password = nil
  end

end

app/models/userpw.rb
class Userpw < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_after_action :verify_authorized
  skip_before_action :authenticate_user!

  def form
  end

  def mail

    if params[:contact]
      email =  params[:contact][:email]
      message = params[:contact][:message]

      if email.present? || message.present?
        ContactMailer.send_contact_email(email, message).deliver_now
        redirect_to '/contact', notice: 'Email sent!'
      else
        flash[:warning] = "Please fill out the form."
        redirect_to '/contact'
      end
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_after_action :verify_authorized

  def index
    @q = Message.ransack(params[:q])
    @messages = @q.result(distinct: true)
  end

  def create
    message = Message.new(message_params)
    message.user = current_user

    @connect = Connect.where("chatroom_id = ? AND user_id = ?", message.chatroom_id, current_user)

    if message.save
      ActionCable.server.broadcast 'messages',
        message: message.content,
        user: message.user.username,
        connect: @connect[0].article
      head :ok
    end
  end

  private

    def message_params
      params.require(:message).permit(:content, :chatroom_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_after_action :verify_authorized

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_after_action :verify_authorized
  skip_before_action :authenticate_user!

  def about
   @chatroom = Chatroom.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/messages/_form.html.erb
<%= form_for message, remote: true, authenticity_token: true do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= f.label :your_message %>
    <%= f.text_field :content, id: "text_area", data: {textarea: "message"}  %>
  </div>

  <%= f.hidden_field :chatroom_id, value: chatroom.id %>

  <div class="actions">
    <%= f.submit "send", style: "display: none", data: {send: "message"}%>
  </div>
<% end %>

app/views/messages/_message.html.erb
<!-- this doesn't work as it'll only hide the message if the browser refreshes if message.user.username == "TestSee" %> -->
<!-- Perhaps I can hide old messages with this? -->
<!--  this is to only display messages that have alredy been saved in the database.-->
<!--  TO DO - I have to change this so it will show the appropriate value of the connects and not just teh same one, I have to change the connects[0] to something else -->
<p><strong><%=message.user.username%></strong>(<span class="agree"><%= message.user.connects[0].article %></span>):  <%=message.content%></p>

app/views/messages/_message_form.html.erb
<%=form_for message, remote: true, authenticity_token: true do |f| %>
  <%= f.label :your_message%>:
  <!--  pressing enter will not work if I remove data: {textarea: "message"}-->
  <%= f.text_area :content, class: "form-control", data: {textarea: "message"}%>

  <%= f.hidden_field :chatroom_id, value: chatroom.id %>
  <%= hidden_field_tag 'connect', @connect %>

  <%= f.submit "send", class: "btn btn-primary", style: "display: none", data: {send: "message"}%>
<%end%>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<%= render 'searches/search' %>


<div class="jumbotron">
  <div class="container">
    <div class="container text-center">
      <h2>Search Results</h2>
    </div>
    <br>
    <table class="table">
      <thead>
        <tr>
          <th><%= sort_link(@q, :username) %></th>
          <th>Chatroom</th>
          <th>Message Content</th>
          <th><%= sort_link(@q, :created_at) %></th>
        </tr>
      </thead>
      <% @messages.each do |message| %>
      <tbody>
        <td><%= message.user.username %></td>
        <td><%= message.chatroom.topic %></td>
        <td><%= message.content %></td>
        <td><%= message.created_at %></td>
      </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user %>
</p>

<p>
  <strong>Chatroom:</strong>
  <%= @message.chatroom %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>Profile</h1>