config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :profiles
  root "welcome#about"

  get '/contact', to: "contacts#form"
  post '/contact', to: "contacts#mail"

  get 'registrations/new'

  # post 'home/action'

  get '/signup', to: "registrations#new"
  post '/signup', to: "registrations#create"

  get 'login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  # get 'users/:id', to: "users#show", as: "profile"

  resources :chatrooms, param: :slug
  resources :messages

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  has_many :connects, dependent: :destroy
  
  validates :topic, presence: true, uniqueness: true, case_sensitive: false
  before_validation :sanitize, :slugify


  def to_param
    self.slug
  end

  def slugify
    self.slug = self.topic.downcase.gsub(" ", "-")
  end

  def sanitize
    self.topic = self.topic.strip
  end
end

app/models/connect.rb
class Connect < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom

  validates :article, presence: true 
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

   mount_uploader :avatar, AvatarUploader
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  attr_accessor :password

  before_save :encrypt_password
  after_save :clear_password


  has_many :messages, dependent: :destroy
  has_many :chatrooms, through: :messages
  has_many :connects, dependent: :destroy
  has_one :profile, dependent: :destroy

  # EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  validates_length_of :password, in: 6..20, on: :create

  after_create :assign_default_role


  def assign_default_role
    self.add_role(:member) if self.roles.blank?
  end

  def admin?
    has_role?(:admin)
  end

  def self.authenticate(username="", login_password="")

    user = User.find_by_username(username)

    if user && user.match_password(login_password)
      return user
    else
      return false
    end
  end

  def match_password(login_password="")
    encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
  end

  def encrypt_password
    unless password.blank?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def clear_password
    self.password = nil
  end

end

app/models/userpw.rb
class Userpw < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_after_action :verify_authorized

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_errors.html.erb
<% if flash.notice %>
  <div class="alert alert-danger">
      <% flash.notice.each do |type, messages|%>
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span><%messages.each do |msg|%>
          <%=type%> <%=msg%>
        <%end%>
      <%end%>
  </div>
<%end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Chatty", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= render partial: 'layouts/navbar_links' %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Engauge</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>

  <div class="container">
    <%= render partial: 'partials/header' %>
    <%= render partial: 'partials/navbar' %>


    <%= yield %>

    <%= render partial: 'partials/footer' %>
  </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<i class="medium material-icons">view_headline</i>

app/views/partials/_flash_errors.html.erb
<% if flash.notice %>
  <div class="alert alert-danger">
      <% flash.notice.each do |type, messages|%>
        <i class="large material-icons" aria-hidden="true">thumb_down</i><%messages.each do |msg|%>
          <%=type%> <%=msg%>
        <%end%>
      <%end%>
  </div>
<%end%>

app/views/partials/_footer.html.erb
<footer class="footer">
    <h4 class="text-muted text-center">Daily News Pty Ltd</h4>
</footer>

app/views/partials/_header.html.erb
<div class="page-header text-center header">
  <%= image_tag ("header_smh.png"), class: "resize" %>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-form">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <button type="button" class="btn btn-default navbar-btn" aria-label="Left Align">
          <a href="/"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a>
      </button>&nbsp;
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= render partial: 'partials/navbar_links' %>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/partials/_navbar_links.html.erb
<ul class="nav navbar-nav">
  <li>
    <button class="btn btn-default navbar-btn">
      <%= link_to "News", new_chatroom_path %>
    </button>&nbsp;
  </li>
  <li>
    <button class="btn btn-default navbar-btn">
      <%= link_to "Sport", new_chatroom_path %>
    </button>&nbsp;
  </li>
  <li>
    <button class="btn btn-default navbar-btn">
      <%= link_to "Business", new_chatroom_path %>
    </button>&nbsp;
  </li>
  <li>
    <button class="btn btn-default navbar-btn">
      <%= link_to "World", new_chatroom_path %>
    </button>&nbsp;
  </li>
  <li>
    <button class="btn btn-default navbar-btn">
      <%= link_to "Politics", new_chatroom_path %>
    </button>&nbsp;
  </li>
  <li>
    <button class="btn btn-default navbar-btn">
      <%= link_to "Comment", new_chatroom_path %>
    </button>&nbsp;
  </li>
  <li>
    <button class="btn btn-default navbar-btn">
      <%= link_to "Property", new_chatroom_path %>
    </button>&nbsp;
  </li>
  <li>
    <button class="btn btn-default navbar-btn">
      <%= link_to "Lifestyle", new_chatroom_path %>
    </button>&nbsp;
  </li>
  <li>
    <button class="btn btn-default navbar-btn">
      <%= link_to "Entertainment", new_chatroom_path %>
    </button>&nbsp;
  </li>
  <li>
    <button class="btn btn-default navbar-btn">
      <%= link_to "Contact", contact_path %>
    </button>&nbsp;
  </li>
  <% if logged_in? %>
  <li>
    <button type="button" class="btn btn-default navbar-btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= link_to "Engaugeus", chatrooms_path %> <span class="caret"></span>
    </button>&nbsp;
    <ul class="dropdown-menu">
      <li><%= link_to "Engaugements", chatrooms_path %></li>
      <li><%= link_to "Profiles", profiles_path %></li>
      <li><%= link_to "New Profile", new_profile_path %></li>
      <li><%= link_to "Search Engauges", messages_path %></li>
      <li role="separator" class="divider"></li>
      <li><%= link_to "Admin Dashboard", rails_admin_path %></li>
      <li><a href="#">Future</a></li>
    </ul>
   </li>
   <li>
     <button class="btn btn-default navbar-btn">
    <%= link_to "Log Out", logout_path, method: "delete" %>
    </button>&nbsp;
   </li>
  <% else %>
  <li>
    <button class="btn btn-default navbar-btn">
      <%= link_to "Extra", new_chatroom_path %>
    </button>&nbsp;
  </li>
  <button class="btn btn-default navbar-btn">
   <li>
    <%= link_to "Sign Up", signup_path %>
   </li>
  </button>
  <button class="btn btn-default navbar-btn">
   <li>
    <%= link_to "Log In", login_path %>
   </li>
  </button>
  <% end %>
</ul>

app/views/partials/_summary1.html.erb
<div class="panel panel-default bootcards-media">
  <div class="panel-heading">
    <h5><%= @object.title %></h5>
  </div>
  <div class="panel-body">
       <%= image_tag @object.images.first.src.to_s, class: "thumbnail image-row" %>
    </a>
  </div>
  <div class="panel-footer dl-horizontal">
    <%= @object.description %>
  </div>
</div>

app/views/partials/_summary2.html.erb
<div class="panel panel-default bootcards-media">
  <div class="panel-heading">
    <h5><%= @summary2.title %></h5>
  </div>
  <div class="panel-body">
       <%= image_tag @summary2.images.first.src.to_s, class: "thumbnail image-row" %>
    </a>
  </div>
  <div class="panel-footer dl-horizontal">
    <%= @summary2.description %>
  </div>
</div>

app/views/partials/_summary3.html.erb
<div class="panel panel-default bootcards-media">
  <div class="panel-heading">
    <h5><%= @summary3.title %></h5>
  </div>
  <div class="panel-body">
       <%= image_tag @summary3.images.first.src.to_s, class: "thumbnail image-row" %>
    </a>
  </div>
  <div class="panel-footer dl-horizontal">
    <%= @summary3.description %>
  </div>
</div>

app/views/partials/_summary4.html.erb
<div class="panel panel-default bootcards-media">
  <div class="panel-heading">
    <h5><%= @summary4.title %></h5>
  </div>
  <div class="panel-body">
       <%= image_tag @summary4.images.first.src.to_s, class: "thumbnail image-row" %>
    </a>
  </div>
  <div class="panel-footer dl-horizontal">
    <%= @summary4.description %>
  </div>
</div>